fun next_playable l = {
  if (list_empty l) {
    end_turn ()
  }
  else {
    var u = list_hd l;
    var acc = accessible_positions u self players map;
    if ((unit_has_played u) || (list_empty acc)) {
      next_playable (list_tl l)
    } else {
      u
    }
  }
}

fun addone a = {a + 1}

var l = list_map addone [1;2;3;4];

var l = list_map addone l;

list_iter print_int l;

print_string "\n";

var l = list_map addone ["a";"b";"c"];

var l = list_map fst [(1,2);(4,5);(9,8)];

list_iter print_int l;

print_string "\n";


move default {
  var acc = accessible_positions selected_unit self players map;
  var n = list_length acc;
  var rnd = rand n;
  dijkstra_to selected_unit map (list_nth acc rnd)
}

attack default {
  do_nothing ()
}

init {
}

main {
  next_playable (army_of self)
}
